name: infra cicd
on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: "us-east-1"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to AWS CloudFormation For Network
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: demo-network
          template: infra/demo-network.yaml
          capabilities: "CAPABILITY_IAM,CAPABILITY_NAMED_IAM"
          no-fail-on-empty-changeset: "1"

      - name: Deploy to AWS CloudFormation For app
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: demo-app
          template: infra/demo-cfn-stack.yaml
          capabilities: "CAPABILITY_IAM,CAPABILITY_NAMED_IAM"
          no-fail-on-empty-changeset: "1"
          parameter-overrides: |
            DB_HOST=${{ secrets.DBHOST }}
            DB_USER=${{ secrets.DBUSER }}
            DB_NAME=${{ secrets.DBNAME }}
            DB_PASSWORD=${{ secrets.DBPASSWORD }}